name: Dockerfile executions

on:
  push:

permissions:
  contents: read

jobs:
  docker-linux-execution:
    runs-on: ubuntu-latest
    env:
      TAG: nwfistere/jsonparce:ci
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
    
      - name: Login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Setup Docker BuildX
        id: setup-buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
          driver: cloud
          endpoint: "nwfistere/nwf"
          version: "lab:latest"

      - name: Build the Container
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          provenance: false
          tags: ${{ env.TAG }}
          file: ./docker/ubuntu/Dockerfile
          outputs: ${{ github.event_name == 'pull_request' && 'type=cacheonly' || 'type=registry' }}

      - name: Run GCC Release Strict
        id: run_gcc_release_strict
        run: |
          docker run -v .:/src -w /src --rm ${{ env.TAG }} /bin/bash -c \
            "./docker/ubuntu/entrypoint.sh \
              -s ON \
              -c /usr/bin/gcc \
              -x /usr/bin/g++ \
              -t 1 \
              -f Release \
              "

      - name: Run GCC Release Non-Strict
        id: run_gcc_release_non_strict
        run: |
          docker run -v .:/src -w /src --rm ${{ env.TAG }} /bin/bash -c \
            "./docker/ubuntu/entrypoint.sh \
              -s OFF \
              -c /usr/bin/gcc \
              -x /usr/bin/g++ \
              -t 1 \
              -f Release \
              "

      - name: Run Clang Release Strict
        id: run_clang_release_strict
        run: |
          docker run -v .:/src -w /src --rm ${{ env.TAG }} /bin/bash -c \
            "./docker/ubuntu/entrypoint.sh \
              -s ON \
              -c /usr/bin/clang \
              -x /usr/bin/clang++ \
              -t 1 \
              -f Release \
              "

      - name: Run Clang Release Non-Strict
        id: run_clang_release_non_strict
        run: |
          docker run -v .:/src -w /src --rm ${{ env.TAG }} /bin/bash -c \
            "./docker/ubuntu/entrypoint.sh \
              -s OFF \
              -c /usr/bin/clang \
              -x /usr/bin/clang++ \
              -t 1 \
              -f Release \
              "