# github actions cannot seem to run windows containers yet,
# so call the entrypoint.ps1 script for now.

name: Windows executions

on:
  push:

permissions:
  contents: read

jobs:
  windows-execution:
    runs-on: windows-latest
    strategy:
      # Set fail-fast to false to ensure that feedback is delivered for all matrix combinations. Consider changing this to true when your workflow is stable.
      fail-fast: true

      matrix:
        build_type: [Release]
        strict_define: [ON, OFF]
        tests_enabled: [ON]
      
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Run Entrypoint
        id: run_entrypoint
        run: .\\docker\\windows\\entrypoint.ps1
              -s ${{ matrix.strict_define }} \
              -t ${{ matrix.tests_enabled }} \
              -c ${{ matrix.build_type }}